name: Create Dev Release on Push

on:
  #schedule:
  # every saturday at 05:07am
  #  - cron: "7 5 * * 0"
  push:
    branches:
      - main

jobs:
  release:
    name: "dev release"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: get repo name
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Get current year, month and day
        id: BUILD_DATE
        run: |
          echo "BUILD_DATE_YEAR=$(date -u +'%Y')" >> $GITHUB_ENV
          echo "BUILD_DATE_MONTH=$(date -u +'%m')" >> $GITHUB_ENV
          echo "BUILD_DATE_DAY=$(date -u +'%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_NUMBER=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_WITH_DOT=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_WITH_HYPHEN=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Replace placeholders with current date
        run: |
          sed -i "s/version = \"dev\"/version = \"${{ env.BUILD_DATE_WITH_DOT }}\"/g" ${{ env.REPO_NAME }}.lua
          sed -i "s/## Version: dev/## Version: ${{ env.BUILD_DATE_WITH_DOT }}/g" ${{ env.REPO_NAME }}.addon
          sed -i "s/## AddOnVersion: 99999999/## AddOnVersion: ${{ env.BUILD_DATE_NUMBER }}/g" ${{ env.REPO_NAME }}.addon

      - name: Create ZIP archive
        run: |
          REPO_FOLDER=$(pwd)
          mkdir -p /tmp/${{ env.REPO_NAME }}
          cp -r ./* /tmp/${{ env.REPO_NAME }}
          rm -rf /tmp/${{ env.REPO_NAME }}/{.git,.github,.gitignore}
          cd /tmp
          zip -r "$REPO_FOLDER/${{ env.REPO_NAME }}-${{ env.BUILD_DATE_WITH_HYPHEN }}-dev.zip" ./${{ env.REPO_NAME }} -x "*.git*" "*.github*" ".gitignore"

      - name: Create GitHub Release
        #id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.BUILD_DATE_WITH_DOT }}-dev"
          commit: ${{ github.ref }}
          tag: "${{ env.BUILD_DATE_WITH_DOT }}-dev"
          artifacts: "${{ env.REPO_NAME }}-${{ env.BUILD_DATE_WITH_HYPHEN }}-dev.zip"
          artifactContentType: application/zip
          bodyFile: CHANGELOG.md
          allowUpdates: true
          makeLatest: true
          prerelease: true
          updateOnlyUnreleased: true
